Задание 1

In [1]:
import numpy as np

In [ ]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis = 0)

In [9]:
mean_a

array([2. , 8.4])

Задание 2

In [10]:
centered_a = a - mean_a

In [11]:
centered_a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [39]:
at = a.T
a.T


array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [34]:
split = np.split(at, 2, axis = 0)
split1 = split[0][0]
split2 = split[1][0]



array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [41]:
a_centered_sp = split1 @ split2
a_centered_sp/4

2.0

Задание 4

In [38]:
ab = np.cov(a.T)
ab

array([[1. , 2. ],
       [2. , 4.3]])